export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'; 
export const LOG_OUT_FAIL = 'LOG_OUT_FAIL'; 
export const AUTO_LOG_IN = 'AUTO_LOG_IN'; 

export const FETCH_SP_START = 'FETCH_SP_START'; 
export const FETCH_SP_SUCCESS = 'FETCH_SP_SUCCESS'; 
export const FETCH_SP_FAIL = 'FETCH_SP_FAIL'; 
export const PURCHASE_SPIN_START = 'PURCHASE_SPIN_START'; 
export const PURCHASE_SPIN_SUCCESS = 'PURCHASE_SPIN_SUCCESS'; 
export const PURCHASE_SPIN_FAIL = 'PURCHASE_SPIN_FAIL'; 
export const RESET_PURCHASE_ERROR = 'RESET_PURCHASE_ERROR'; 
export const RESET_DEGREE = 'RESET_DEGREE'; 

export const FETCH_INVENTORY_START = 'FETCH_INVENTORY_START'; 
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS'; 
export const FETCH_INVENTORY_FAIL = 'FETCH_INVENTORY_FAIL'; 

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START'; 
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'; 
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'; 
